apply plugin: 'com.android.application'

android {
    namespace 'com.pawstclass.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.pawstclass.app"
        minSdk 21
        targetSdk 35
        versionCode 7
        versionName "1.6"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
